# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

회사내에서 바로 사용하고 싶다면 tensorflow  

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [9]:
x = np.array(range(0,20))
y = x * 2 -1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [11]:
x.shape, y.shape #숫자 1이 있다고 생각해라 

((20,), (20,))

((20,)) -> 1 생략  
input  
(shape(1,))  
output  
Dense(1)

모델링 4가지 단계

In [3]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언, 레이어 블록을 쌓을 발판 생성
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) ) # input layer
model.add( keras.layers.Dense(1) ) #output layer

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 : 모델이 어떻게 동작할지 알려주는 단계
# loss = cost 평가 지표, 무엇으로 비교할지를 정하는 것
# 회귀 -> mse 평가 지표 문자열 형태로 넣기 
# 옵티마이저 = 경사하강법 , 얼마나 이쁘게 진행할지를 정하는 단계
model.compile(loss='mse', 
              optimizer='adam')

In [12]:
# 모델학습
# 학습 과정이기 때문에 x,y 
# epochs : 학습 데이터를 몇번이나 학습 시킬래? 
# verbose : 1 -> 학습 과정 processbar로 보여줌 
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 15ms/step - loss: 506.0732
Epoch 2/10
1/1 [==============================] - 0s 21ms/step - loss: 505.5358
Epoch 3/10
1/1 [==============================] - 0s 12ms/step - loss: 504.9989
Epoch 4/10
1/1 [==============================] - 0s 14ms/step - loss: 504.4622
Epoch 5/10
1/1 [==============================] - 0s 13ms/step - loss: 503.9259
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 503.3900
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 502.8544
Epoch 8/10
1/1 [==============================] - 0s 11ms/step - loss: 502.3192
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 501.7844
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 501.2498


In [5]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [6]:
# 모델 예측 
model.predict(x).reshape(-1)

array([ 0.00999821, -0.09143678, -0.19287178, -0.29430676, -0.39574176,
       -0.49717677, -0.5986117 , -0.7000467 , -0.8014817 , -0.9029167 ,
       -1.0043517 , -1.1057867 , -1.2072216 , -1.3086567 , -1.4100916 ,
       -1.5115267 , -1.6129616 , -1.7143966 , -1.8158317 , -1.9172666 ],
      dtype=float32)

## Now, Your turn!

In [14]:
#라이브러리 불러오기
import tensorflow as tf 
import numpy as np
from tensorflow import keras #내장되어 있는 keras

In [15]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [28]:
keras.backend.clear_session()
model=keras.models.Sequential()
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1))
model.compile(loss='mse', optimizer='adam')

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.fit(x,y,epochs=10,verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 368ms/step - loss: 133.0915
Epoch 2/10
1/1 [==============================] - 0s 19ms/step - loss: 132.8504
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 132.6096
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 132.3691
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 132.1289
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 131.8890
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 131.6494
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 131.4101
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 131.1712
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 130.9326


In [31]:
y_pred=model.predict(x)

In [36]:
y_pred[:5].reshape(-1)

array([-0.00999438, -1.3235795 , -2.6371646 , -3.9507496 , -5.264335  ],
      dtype=float32)

In [37]:
y[:5]

array([0, 0, 0, 0, 0])

## Quick Logistic Regression!

In [38]:
import tensorflow as tf
import tensorflow.keras as keras

import numpy as np

In [39]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [44]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )


# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
# 이진 분류 -> crossentropy
model.compile(loss = 'binary_crossentropy',
              optimizer = 'adam',
              metrics=['accuracy'])

In [48]:
# 데이터를 넣어서 학습시키자!
#model.fit(x[:15], y[:15], epochs=10, verbose=1)
model.fit(x, y, epochs=10, verbose=1)
# 결과 출력해줘!
print(y[:5])
print(model.predict(x[:5]).reshape(-1)) # threshold가 0.5보다 크면 1이 된당 하지만 여기서는 확률값으로 보여줌 

Epoch 1/10
1/1 [==============================] - 0s 18ms/step - loss: 2.8805 - accuracy: 0.4500
Epoch 2/10
1/1 [==============================] - 0s 14ms/step - loss: 2.8731 - accuracy: 0.4500
Epoch 3/10
1/1 [==============================] - 0s 20ms/step - loss: 2.8658 - accuracy: 0.4500
Epoch 4/10
1/1 [==============================] - 0s 16ms/step - loss: 2.8585 - accuracy: 0.4500
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 2.8511 - accuracy: 0.4500
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 2.8438 - accuracy: 0.4500
Epoch 7/10
1/1 [==============================] - 0s 13ms/step - loss: 2.8365 - accuracy: 0.4500
Epoch 8/10
1/1 [==============================] - 0s 20ms/step - loss: 2.8291 - accuracy: 0.4500
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 2.8218 - accuracy: 0.4500
Epoch 10/10
1/1 [==============================] - 0s 12ms/step - loss: 2.8145 - accuracy: 0.4500
[0 0 0 0 0]
[0.50996834 0.4178

0과 1이 아닌 확률값으로 보여줌  
loss는 계속해서 줄어들어야 정상  

## Now, Your turn!

In [42]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [49]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [50]:
keras.backend.clear_session()

In [54]:
from numpy.core.fromnumeric import shape
model=keras.models.Sequential()
model.add( keras.layers.Input(shape=(1,)) ) #input이 functional이기 때문
model.add( keras.layers.Dense(1, activation='sigmoid') )

In [55]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [56]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy']) 
# 평가 지표를 accuracy만 볼 수 있는게 아님, 여러개를 확인하고 싶다면 리스트로 넣어줘야한다. 

In [57]:
model.fit(x,y,epochs=10,verbose=1)

Epoch 1/10
2/2 [==============================] - 1s 8ms/step - loss: 0.6073 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 5ms/step - loss: 0.6036 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 12ms/step - loss: 0.6003 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 7ms/step - loss: 0.5983 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 7ms/step - loss: 0.5960 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 10ms/step - loss: 0.5944 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 6ms/step - loss: 0.5931 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 5ms/step - loss: 0.5920 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 5ms/step - loss: 0.5914 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 5ms/step - loss: 0.5907 - accuracy: 0.5250


In [59]:
model.predict(x[:5]).reshape(-1)

array([0.49573013, 0.5046387 , 0.51354426, 0.52244127, 0.5313241 ],
      dtype=float32)

In [60]:
y[:5]

array([0, 0, 0, 0, 0])