# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [3]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss = 'mse', optimizer = 'adam')

In [4]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 523ms/step - loss: 732.7749
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 732.1277
Epoch 3/10
1/1 [==============================] - 0s 13ms/step - loss: 731.4809
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 730.8344
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 730.1881
Epoch 6/10
1/1 [==============================] - 0s 11ms/step - loss: 729.5422
Epoch 7/10
1/1 [==============================] - 0s 19ms/step - loss: 728.8966
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 728.2513
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 727.6063
Epoch 10/10
1/1 [==============================] - 0s 9ms/step - loss: 726.9617


In [5]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
[ 0.00999851 -0.49233562 -0.99466974 -1.4970038  -1.9993379  -2.501672
 -3.0040061  -3.5063403  -4.0086746  -4.5110087  -5.013343   -5.515677
 -6.018011   -6.520345   -7.0226793  -7.5250134  -8.027348   -8.529682
 -9.032016   -9.534349  ]


## Now, Your turn!

In [6]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [10]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)
x.shape,y.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


((20,), (20,))

In [8]:
keras.backend.clear_session()

input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss = 'mse', optimizer = 'adam')

In [9]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 290ms/step - loss: 87.5888
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 87.4079
Epoch 3/10
1/1 [==============================] - 0s 9ms/step - loss: 87.2272
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 87.0469
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 86.8669
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 86.6872
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 86.5078
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 86.3288
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 86.1500
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 85.9716


## Quick Logistic Regression!

In [11]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [12]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [13]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [14]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
1/1 [==============================] - 0s 458ms/step - loss: 3.1151 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 3.1124 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 8ms/step - loss: 3.1097 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 3.1070 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 3.1043 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 3.1016 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 9ms/step - loss: 3.0989 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 3.0962 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 3.0935 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 3.0908 - accuracy: 0.5500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1

## Now, Your turn!

In [15]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [17]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)
x.shape,y.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


((40,), (40,))

In [18]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [19]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [20]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
2/2 [==============================] - 0s 7ms/step - loss: 6.7346 - accuracy: 0.5250
Epoch 2/10
2/2 [==============================] - 0s 6ms/step - loss: 6.7243 - accuracy: 0.5250
Epoch 3/10
2/2 [==============================] - 0s 6ms/step - loss: 6.7143 - accuracy: 0.5250
Epoch 4/10
2/2 [==============================] - 0s 5ms/step - loss: 6.7037 - accuracy: 0.5250
Epoch 5/10
2/2 [==============================] - 0s 5ms/step - loss: 6.6935 - accuracy: 0.5250
Epoch 6/10
2/2 [==============================] - 0s 5ms/step - loss: 6.6833 - accuracy: 0.5250
Epoch 7/10
2/2 [==============================] - 0s 6ms/step - loss: 6.6735 - accuracy: 0.5250
Epoch 8/10
2/2 [==============================] - 0s 7ms/step - loss: 6.6632 - accuracy: 0.5250
Epoch 9/10
2/2 [==============================] - 0s 7ms/step - loss: 6.6535 - accuracy: 0.5250
Epoch 10/10
2/2 [==============================] - 0s 4ms/step - loss: 6.6429 - accuracy: 0.5250
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

커스텀하고 싶을때 funcational 사용  