# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [12]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [13]:
#세션 클리어
keras.backend.clear_session()

#레이어 사슬처럼 엮기
il=keras.layers.Input(shape=(13,))
ol=keras.layers.Dense(1)(il)

#모델의 시작과 끝 지정
model=keras.models.Model(inputs=il,outputs=ol)

#컴파일
model.compile(loss='mse',optimizer='adam')


In [14]:
#학습
model.fit(x,y,verbose=1,epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 3ms/step - loss: 684.6711
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 519.2627
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 420.2147
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 336.2881
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 267.6869
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 216.1988
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 176.6808
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 148.6873
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 128.0187
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 114.3572


In [15]:
model.predict(x[:5]).reshape(-1)

array([31.31474 , 21.240929, 24.009014, 24.28864 , 22.970264],
      dtype=float32)

In [16]:
y[:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

# Logistic Regression 쬐금 더 어려운 데이터

In [17]:
from sklearn.datasets import load_breast_cancer

In [18]:
cancer = load_breast_cancer()

In [20]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape,y.shape

((569, 30), (569,))

In [21]:
keras.backend.clear_session()
il=keras.layers.Input(shape=(30,))
ol=keras.layers.Dense(1,activation='sigmoid')(il)
model=keras.models.Model(inputs=il,outputs=ol)
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')

In [22]:
model.fit(x,y,verbose=1,epochs=10)

Epoch 1/10
18/18 [==============================] - 1s 2ms/step - loss: 54.5977 - accuracy: 0.3726
Epoch 2/10
18/18 [==============================] - 0s 2ms/step - loss: 40.2757 - accuracy: 0.3726
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 26.1374 - accuracy: 0.3726
Epoch 4/10
18/18 [==============================] - 0s 2ms/step - loss: 11.6935 - accuracy: 0.4060
Epoch 5/10
18/18 [==============================] - 0s 2ms/step - loss: 1.7788 - accuracy: 0.7452
Epoch 6/10
18/18 [==============================] - 0s 2ms/step - loss: 0.6260 - accuracy: 0.9033
Epoch 7/10
18/18 [==============================] - 0s 2ms/step - loss: 0.6132 - accuracy: 0.9016
Epoch 8/10
18/18 [==============================] - 0s 2ms/step - loss: 0.5613 - accuracy: 0.9104
Epoch 9/10
18/18 [==============================] - 0s 2ms/step - loss: 0.5459 - accuracy: 0.9069
Epoch 10/10
18/18 [==============================] - 0s 2ms/step - loss: 0.5510 - accuracy: 0.9086


In [25]:
model.predict(x[:5]).reshape(-1)

array([0.0000000e+00, 3.7326117e-30, 3.7395618e-25, 9.9785322e-01,
       8.2361957e-17], dtype=float32)

In [24]:
y[:5]

array([0, 0, 0, 0, 0])