# 멀티클래스 분류 연습 (over 2진분류)

![iris_flower](https://www.embedded-robotics.com/wp-content/uploads/2022/01/Iris-Dataset-Classification-1024x367.png)

Tensorflow + Keras  
1. Sequential API  
2. Funtional API   
-> 선형회귀, 로지스틱회귀  
로지스틱회귀 -> 'sigmoid' 0과 1 사이로 만들기, 'binary_crossentropy',''accuracy'  

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()

In [ ]:
x = iris.data
y = iris.target

In [ ]:
x.shape, y.shape

((150, 4), (150,))

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

숫자로써 의미가 있는 0,1,2???

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

integer encoding 되어 있는 형태  -> 범주형 데이터  
0~1 *2 ? 이게 맞는거야?  
NO!!!  
수치형 데이터와 범주형 데이터의 혼동  
각 클래스 별로 로지스틱 회귀를 해보자!!  
1. setoas or not -> 0.9 -> 0.9
2. vesicolor or not -> 0.8 -> 0.09
3. virginica or not -> 0.2 -> 0.01  
각 클래스별로 확률을 구해줌    
  0.9+0.8+0.2=190%?? 안되징 -> 다른 함수 사용 (softmax)

In [ ]:
# One-Hot Encoding
from tensorflow.keras.utils import to_categorical

setosa, versicolor, viginica 과연 각자 하는가?  
0~1?  

In [ ]:
y = to_categorical(y, 3)

In [ ]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
x.shape, y.shape

((150, 4), (150, 3))

# 1번. Sequential API style로 모델링 하세요

    loss = 'categorical_crossentropy' 사용!

In [ ]:
from tensorflow import keras
import tensorflow as tf
import numpy as np
import pandas as pd

In [ ]:
keras.backend.clear_session()
model=keras.models.Sequential()
model.add(keras.layers.Input(shape=(4,)))
model.add(keras.layers.Dense(3,activation='softmax'))
model.compile(loss=keras.losses.categorical_crossentropy,metrics='accuracy',optimizer='adam') #다중 클래스

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x,y,verbose=0,epochs=10)

In [ ]:
model.predict(x[:5])

array([[0.06858829, 0.13517714, 0.79623455],
       [0.11922882, 0.1293156 , 0.75145555],
       [0.08299381, 0.15143616, 0.76557004],
       [0.10255398, 0.13097428, 0.76647174],
       [0.05859413, 0.14004861, 0.80135727]], dtype=float32)

In [ ]:
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

# 2번. Functional API style로 모델링 하세요

In [ ]:
x.shape, y.shape

((150, 4), (150, 3))

In [ ]:
from tensorflow.python import metrics
keras.backend.clear_session()
il=keras.layers.Input(shape=(4,))
ol=keras.layers.Dense(3,activation='softmax')(il)
model=keras.models.Model(inputs=il,outputs=ol)
model.compile(loss="categorical_crossentropy",metrics='accuracy',optimizer='adam')
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x,y,verbose=1,epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 2.5831 - accuracy: 0.1200
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 2.5527 - accuracy: 0.1067
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 2.5201 - accuracy: 0.1067
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: 2.4874 - accuracy: 0.1133
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 2.4582 - accuracy: 0.1133
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 2.4262 - accuracy: 0.1133
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 2.3949 - accuracy: 0.1133
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 2.3631 - accuracy: 0.1133
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 2.3328 - accuracy: 0.1133
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 2.3003 - accuracy: 0.1067


In [ ]:
model.predict(x[:5])

array([[0.00519169, 0.10896489, 0.88584346],
       [0.00875827, 0.12848397, 0.8627578 ],
       [0.00787169, 0.12726696, 0.86486137],
       [0.00927051, 0.15777521, 0.83295435],
       [0.00497082, 0.1128599 , 0.8821693 ]], dtype=float32)

In [ ]:
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)