# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [1]:
from sklearn.datasets import load_boston

In [2]:
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [3]:
x = boston.data
y = boston.target

In [4]:
x.shape, y.shape

((506, 13), (506,))

In [5]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [6]:
########
# 모델링
########

model=keras.models.Sequential()
model.add(keras.layers.Input(shape=(13,)))
model.add(keras.layers.Dense(1))
model.compile(loss='mse',optimizer='adam')

In [10]:
model.summary() #14 ; 13+ bias 포함

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 14        
                                                                 
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [7]:
###########
# 모델 학습
###########
model.fit(x,y,epochs=10)

Epoch 1/10
16/16 [==============================] - 1s 2ms/step - loss: 25836.4004
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 21364.8672
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 17482.7070
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 14095.8271
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 11282.7803
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 8897.1719
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 6945.2681
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 5365.9907
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 4092.4402
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 3086.8210


In [9]:
###########
# 모델 예측
###########
print(model.predict(x[:4]))
print(y[:4])

[[69.6172 ]
 [64.50958]
 [65.44362]
 [63.35846]]
[24.  21.6 34.7 33.4]


# 히든 레이어 추가하여 모델링!

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [15]:
########
# 모델링
########
keras.backend.clear_session()
model=keras.models.Sequential()
model.add(keras.layers.Input(shape=(13,)))
model.add(keras.layers.Dense(32,activation='relu'))
model.add(keras.layers.Dense(32,activation='relu'))
model.add(keras.layers.Dense(1))
model.compile(loss='mse',optimizer='adam')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                448       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,537
Trainable params: 1,537
Non-trainable params: 0
_________________________________________________________________


13+1  
32*(32+1)  
32+1  

In [16]:
###########
# 모델 학습
###########
model.fit(x,y,epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 3ms/step - loss: 498.0048
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 108.2141
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 79.2673
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 72.7409
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 67.6835
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 66.8881
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 66.8774
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 63.8257
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 63.1453
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 59.4886


In [17]:
###########
# 모델 예측
###########
print(model.predict(x[:4]))
print(y[:4])

[[25.532064]
 [27.93374 ]
 [28.683783]
 [28.956945]]
[24.  21.6 34.7 33.4]
